export const REGISTER_REQUEST = 'REGISTER/REQUEST';
export const REGISTER_SUCCESS = 'REGISTER/SUCCESS';
export const REGISTER_FAILURE = 'REGISTER/FAILURE';

export const LOGIN_REQUEST = 'LOGIN/REQUEST';
export const LOGIN_SUCCESS = 'LOGIN/SUCCESS';
export const LOGIN_FAILURE = 'LOGIN/FAILURE';

export const LOGOUT = 'USERS/LOGOUT';

export const ALERT_SUCCESS = 'ALERT/SUCCESS';
export const ALERT_ERROR = 'ALERT/ERROR';
export const ALERT_CLEAR = 'ALERT/CLEAR';

export const RECORD_REQUEST = 'RECORD/REQUEST';
export const RECORD_SUCCESS = 'RECORD/SUCCESS';
export const RECORD_FAILURE = 'RECORD/FAILURE';

export const GET_RECORDS_REQUEST = 'GET_RECORDS/REQUEST';
export const GET_RECORDS_REQUEST_SUCCESS = 'GET_RECORDS/SUCCESS';
export const GET_RECORDS_REQUEST_FAILURE = 'GET_RECORDS/FAILURE';

export const DELETE_RECORDS_REQUEST = 'DELETE_RECORDS/REQUEST';
export const DELETE_RECORDS_REQUEST_SUCCESS = 'DELETE_RECORDS/SUCCESS';
export const DELETE_RECORDS_REQUEST_FAILURE = 'DELETE_RECORDS/FAILURE';

export const UPDATE_RECORDS_REQUEST = 'UPDATE_RECORDS/REQUEST';
export const UPDATE_RECORDS_REQUEST_SUCCESS = 'UPDATE_RECORDS/SUCCESS';
export const UPDATE_RECORDS_REQUEST_FAILURE = 'UPDATE_RECORDS/FAILURE';

export const CREATE_DESCRIPTION = 'RECORD/CREATE_DESCRIPTION';
export const CREATE_DURATION = 'RECORD/CREATE_DURATION';
export const CREATE_TIME_START = 'RECORD/CREATE_TIME_START';
export const CREATE_TIME_FINISH = 'RECORD/CREATE_TIME_FINISH';

export const GET_FILTERED_RECORDS = 'GET_RECORDS/FILTER';
export const RESET_FILTERED_RECORDS = 'RESET_RECORDS/FILTER';
export const SORT_RECORDS = 'RECORDS/SORT';
